package com.dinua.euler.project.problems;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
public class Problem2 {
	private final static int LIMIT = 4 * 1000 * 1000;

	public static void main(String[] args) {
		int elem1 = 1;
		int elem2 = 2;
		int sum = 0;
		while (elem2 < LIMIT) {
			final int aux = elem1;
			elem1 = elem2;
			elem2 = elem2 + aux;

			if (elem1 % 2 == 0) {
				sum = sum + elem1;
			}
		}
		System.out.println(sum);

	}

}
