package prob;
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * @author adi
 *
 */
public class P2 {

	private final int n=4*1000*1000;
	public P2() {
		int elem1=1;
		int elem2=2;
            int sum=0;
		while(elem2<n){
			int aux=elem1;
			elem1=elem2;
			elem2=elem2+aux;
			
			if(elem1%2==0)
				sum=sum+elem1;
		}
		System.out.println(sum);
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
new P2();
	}

}
